// AUTO-GENERATED by scripts/abi-sync.mjs — do not edit by hand.
export const rotaFactoryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "circleImplementation_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "goalPotImplementation_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "registry_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "circleCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "circleImplementation",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "circles",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createCircle",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct RotaCircle.CircleParams",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "contributionAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memberCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "roundDuration",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mode",
            "type": "uint8",
            "internalType": "enum RotaCircle.Mode"
          },
          {
            "name": "collateralBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "givingBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "givingRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "bidWindowBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxDiscountBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "openDeadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "inviteOnly",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "circle",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createGoalPot",
    "inputs": [
      {
        "name": "p",
        "type": "tuple",
        "internalType": "struct GoalPot.PotParams",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memberCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minContribution",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "earlyExitHaircutBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "givingBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "givingRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "inviteOnly",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "pot",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getCircles",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getGoalPots",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "goalPotCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "goalPotImplementation",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "goalPots",
    "inputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isRotaContract",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ReputationRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "CircleCreated",
    "inputs": [
      {
        "name": "circle",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "organizer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "params",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct RotaCircle.CircleParams",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "contributionAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memberCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "roundDuration",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mode",
            "type": "uint8",
            "internalType": "enum RotaCircle.Mode"
          },
          {
            "name": "collateralBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "givingBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "givingRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "bidWindowBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxDiscountBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "openDeadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "inviteOnly",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GoalPotCreated",
    "inputs": [
      {
        "name": "pot",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "organizer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "params",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct GoalPot.PotParams",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "targetAmount",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "memberCap",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minContribution",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "earlyExitHaircutBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "givingBps",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "givingRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "inviteOnly",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "FailedDeployment",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientBalance",
    "inputs": [
      {
        "name": "balance",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "needed",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
