/**
 * Single source of truth for chain config and contract addresses.
 * All values researched from docs.arc.io — see docs/ARC_NOTES.md.
 * Switch networks with VITE_CHAIN=local|arc (see .env.example).
 */
import { defineChain, type Address } from "viem";
import arcDeployments from "./deployments.arc.json";

// deployments.local.json is generated by `pnpm deploy:local` (gitignored); load
// lazily via glob so the app still builds before the first local deployment.
const localFiles = import.meta.glob("./deployments.local.json", { eager: true });
const localDeployments = (localFiles["./deployments.local.json"] as
  | { default: Deployments }
  | undefined)?.default;

export interface Deployments {
  chainId: number;
  usdc: Address;
  reputationRegistry: Address;
  circleImplementation: Address;
  goalPotImplementation: Address;
  factory: Address;
}

/** Arc Testnet — values from docs/ARC_NOTES.md (docs.arc.io, fetched 2026-07-11). */
export const arcTestnet = defineChain({
  id: 5042002,
  name: "Arc Testnet",
  nativeCurrency: {
    name: "USDC",
    symbol: "USDC",
    // native layer uses 18 decimals; the ERC-20 interface (what Rota uses) is 6
    decimals: 18,
  },
  rpcUrls: {
    default: {
      http: ["https://rpc.testnet.arc.network"],
      webSocket: ["wss://rpc.testnet.arc.network"],
    },
  },
  blockExplorers: {
    default: { name: "Arcscan", url: "https://testnet.arcscan.app" },
  },
  contracts: {
    multicall3: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" },
  },
  testnet: true,
});

/** Local anvil chain. No multicall3 entry: reads fall back to plain eth_call. */
export const localAnvil = defineChain({
  id: 31337,
  name: "Anvil (local)",
  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  rpcUrls: { default: { http: ["http://127.0.0.1:8545"] } },
  testnet: true,
});

export type ChainKey = "local" | "arc";
export const CHAIN_KEY: ChainKey = import.meta.env.VITE_CHAIN === "arc" ? "arc" : "local";

export const activeChain = CHAIN_KEY === "arc" ? arcTestnet : localAnvil;

const emptyDeployments: Deployments = {
  chainId: 31337,
  usdc: "0x0000000000000000000000000000000000000000",
  reputationRegistry: "0x0000000000000000000000000000000000000000",
  circleImplementation: "0x0000000000000000000000000000000000000000",
  goalPotImplementation: "0x0000000000000000000000000000000000000000",
  factory: "0x0000000000000000000000000000000000000000",
};

export const deployments: Deployments =
  CHAIN_KEY === "arc" ? (arcDeployments as Deployments) : (localDeployments ?? emptyDeployments);

export const FAUCET_URL = "https://faucet.circle.com";

export function explorerAddressUrl(address: string): string | undefined {
  const base = activeChain.blockExplorers?.default.url;
  return base ? `${base}/address/${address}` : undefined;
}

export function explorerTxUrl(hash: string): string | undefined {
  const base = activeChain.blockExplorers?.default.url;
  return base ? `${base}/tx/${hash}` : undefined;
}
