#!/usr/bin/env node
/**
 * Syncs contract ABIs and deployment addresses from Foundry output into the app.
 * No manual copying, ever:
 *   contracts/out/<Name>.sol/<Name>.json  →  app/src/abi/<name>.ts   (as const, typed)
 *   contracts/deployments/{local,arc}.json → app/src/config/deployments.{local,arc}.json
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts", "out");
const abiDir = join(root, "app", "src", "abi");
mkdirSync(abiDir, { recursive: true });

const contracts = ["RotaFactory", "RotaCircle", "GoalPot", "ReputationRegistry", "MockUSDC"];

for (const name of contracts) {
  const artifactPath = join(out, `${name}.sol`, `${name}.json`);
  if (!existsSync(artifactPath)) {
    console.error(`missing artifact ${artifactPath} — run \`forge build\` first`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(artifactPath, "utf8"));
  const varName = name[0].toLowerCase() + name.slice(1) + "Abi";
  const ts = `// AUTO-GENERATED by scripts/abi-sync.mjs — do not edit by hand.\nexport const ${varName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(abiDir, `${varName}.ts`), ts);
  console.log(`abi  ✓ ${varName}.ts`);
}

writeFileSync(
  join(abiDir, "index.ts"),
  `// AUTO-GENERATED by scripts/abi-sync.mjs — do not edit by hand.\n` +
    contracts.map((n) => `export * from "./${n[0].toLowerCase() + n.slice(1)}Abi";`).join("\n") +
    "\n"
);

for (const net of ["local", "arc"]) {
  const src = join(root, "contracts", "deployments", `${net}.json`);
  if (existsSync(src)) {
    writeFileSync(join(root, "app", "src", "config", `deployments.${net}.json`), readFileSync(src));
    console.log(`addr ✓ deployments.${net}.json`);
  }
}
console.log("abi-sync complete");
